### ISSUE TITLE
Provider times out after exactly 2 hours

### ISSUE THREAD

**Issue by gbernady** [aws-cloudformation/cloudformation-cli-go-plugin#183]
I wrote a resource provider that wraps a very time consuming operation and noticed that the provider always times out after exactly 2 hours. From the limited logs available in CloudWatch it looks like CloudFormation just suddenly stops invoking the CREATE or UPDATE handler, and reports timeout instead.

I managed to reproduce it with a very simple [sample_project.zip](https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/files/5603307/wat.zip) that just returns IN_PROGRESS for 2.5h.

The CloudFormation template I used is:
```yaml
AWSTemplateFormatVersion: 2010-09-09
Resources:
  Inst0:
    Type: 'Foo::Bar::Resource'
  Inst1:
    Type: 'Foo::Bar::Resource'
  Inst2:
    Type: 'Foo::Bar::Resource'
  Inst3:
    Type: 'Foo::Bar::Resource'
  Inst4:
    Type: 'Foo::Bar::Resource'
  Inst5:
    Type: 'Foo::Bar::Resource'
  Inst6:
    Type: 'Foo::Bar::Resource'
  Inst7:
    Type: 'Foo::Bar::Resource'
  Inst8:
    Type: 'Foo::Bar::Resource'
  Inst9:
    Type: 'Foo::Bar::Resource'
```

Here's a [stack_events.log](https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/files/5603367/stack_events.log) file from when I reproduced the issue. According to the [CloudFormation CLI docs](https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/what-is-cloudformation-cli.html), the timeout should be 36h or 48h. Am I missing something?
